#! /bin/bash
#
# Copyright (c) 2014-2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#

source "$(cd "$(dirname "${0}")" && pwd -P)"/../tech-support.functions

header INTERFACES

header Interfaces "$DEFAULT_VRF_NAME"
do_cmd run show interfaces





